ClockWise/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls', namespace='todolist')),
    path('clock/', include('clock.urls', namespace='clock')),
    path('account/', include('users.urls', namespace='users')),
    path('thoughts/', include('thoughts.urls', namespace='thoughts'))
    
]

clock/urls.py
from django.urls import path 
from . import views

app_name = 'clock'

urlpatterns = [
    path("", views.Clock.as_view(), name="clock"),
    path("alarm", views.Alarm.as_view(), name="alarm"),
    path("stopwatch", views.StopWatch.as_view(), name="stopwatch"),
    path("pomodoro", views.Pomodoro.as_view(), name="pomodoro"),
    path("timer", views.Timer.as_view(), name="timer"),
    path("worldclock", views.WorldClock.as_view(), name="worldclock")
]

thoughts/urls.py
from django.urls import path 
from . import views

app_name = 'thoughts'

urlpatterns = [
    path('', views.Thoughts.as_view(), name="thoughts"),
    path('write', views.Write.as_view(), name="write"),
    path('library', views.Library.as_view(), name="library"),
    path('categories', views.Categories.as_view(), name="categories"),
    path('archived', views.Archived.as_view(), name="archived")
]

todolist/urls.py
from django.urls import path 
from . import views

app_name = 'todolist'

urlpatterns = [
    path('', views.Today.as_view(), name="today"),
    path('starred', views.Starred.as_view(), name="starred"),
    path('schedule', views.Schedule.as_view(), name="schedule"),
    path('completed', views.Completed.as_view(), name="completed"),
    path('all', views.All.as_view(), name="all"),
    path('overdue', views.Overdue.as_view(), name="overdue"),
    path('create-task/', views.CreateTask.as_view(), name='create_task'),
    path('delete/<slug:title>/', views.DeleteTask.as_view(), name='delete_task'),
]

users/urls.py
from django.urls import path 
from . import views

app_name = "users"

urlpatterns = [
    path('', views.Profile.as_view(), name="profile"),
    path('signup', views.Register.as_view(), name="signup"),
    path('login/', views.Login.as_view(), name="login"),
]

clock/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

clock/views.py
from django.shortcuts import render
from django.views import View 

# Create your views here.


class Clock(View):
    def get(self, request):
        return render(request, "clock/clock.html")
    
class Alarm(View):
     def get(self, request):
         return render(request, "clock/alarm.html")
     
     
class Pomodoro(View):
    def get(self, request):
        return render(request, "clock/pomodoro.html")
    
class StopWatch(View):
    def get(self, request):
        return render(request, "clock/stopwatch.html")
    

class Timer(View):
    def get(self, request):
        return render(request, "clock/timer.html")
    
class WorldClock(View):
    def get(self, request):
        return render(request, "clock/worldclock.html")
    

clock/templates/clock/alarm.html
{% extends 'clock/clock.html' %}
{% load static %}
{% block title %}Alarm{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}
    

clock/templates/clock/clock.html
{% extends 'shared/layout.html' %}
{% load static %}
{% block title %}Clock{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% block nav %}
<!-- Sidebar Menu Pane -->
<div class="menu-pane fixed top-0 left-[-30vw] bg-black text-white w-[17vw] h-full transition-transform duration-300 ease-in-out">
    <div class="p-5">
         <div class="text-white mb-6 mt-12">
            <input type="text" placeholder="Search" class="w-full p-2 bg-gray-700 text-white rounded">
        </div> 
        
            <!-- Menu Items -->
            <ul class="space-y-4">
                <li class="flex items-center">
                    <i class="fas fa-clock mr-3"></i>
                    <a href="{% url 'clock:clock' %}" class="text-white hover:text-gray-400">Clock</a>
                </li>
                <li class="flex items-center">
                    

                    <i class="fas fa-bell mr-3"></i>
                    <a href="{% url 'clock:alarm' %}" class="text-white hover:text-gray-400">Alarm</a>
                </li>
                
                <li class="flex items-center">
                    
                    
                    <i class="fas fa-clock-rotate-left mr-3"></i>
                    <a href="{% url 'clock:pomodoro' %}" class="text-white hover:text-gray-400">Pomodoro</a>
                    
                </li>
                <li class="flex items-center"> 
                    <i class="fas fa-stopwatch-20 mr-3"></i>
                    <a href="{% url 'clock:stopwatch' %}" class="text-white hover:text-gray-400">Stopwatch</a>
                </li>
                <li class="flex items-center">
                    
                    
                    <i class="fas fa-stopwatch mr-3"></i>
                    <a href="{% url 'clock:timer' %}" class="text-white hover:text-gray-400">Timer</a>
                   
                </li>
                <li class="flex items-center">
                   
                    <i class="fas fa-globe mr-3"></i>
                    <a href="{% url 'clock:worldclock' %}" class="text-white hover:text-gray-400">WorldClock</a>
                    
                </li>
            </ul> 

    </div>
    <!-- Bottom Icons -->
    <div class="absolute bottom-0 w-full flex justify-around py-4 text-white">
        <!-- Clock Icon -->
        <div class="text-center">
            <a href="{% url 'todolist:today' %}" class="text-white hover:text-gray-400">
                <i class="fas fa-clipboard-list fa-2x"></i>
            </a>
            <p class="text-sm mt-1">TODO</p>
        </div>
        
        <!-- Thoughts Icon -->
        <div class="text-center">
            <a href="{% url 'thoughts:thoughts' %}" class="text-white hover:text-gray-400">
                <i class="fas fa-lightbulb fa-2x"></i>
            </a>
            <p class="text-sm mt-1">Thoughts</p>
        </div>
        
        <!-- Profile Icon -->
        <div class="text-center">
            <a href="{% url 'users:profile' %}" class="text-white hover:text-gray-400">
                <i class="fas fa-user fa-2x"></i>
            </a>
            <p class="text-sm mt-1">Profile</p>
        </div>
    </div>
</div>

{% endblock nav%}
{% endblock body %}
    

clock/templates/clock/pomodoro.html
{% extends 'clock/clock.html' %}
{% load static %}
{% block title %}Pomodoro{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}
    

clock/templates/clock/stopwatch.html
{% extends 'clock/clock.html' %}
{% load static %}
{% block title %}Stop Watch{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}
    

clock/templates/clock/timer.html
{% extends 'shared/layout.html' %}
{% load static %}
{% block title %}Timer{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}
    

clock/templates/clock/worldclock.html
{% extends 'clock/clock.html' %}
{% load static %}
{% block title %}World Clock{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}
    