ClockWise/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls', namespace='todolist')),
    path('clock/', include('clock.urls', namespace='clock')),
    path('account/', include('users.urls', namespace='users')),
    path('thoughts/', include('thoughts.urls', namespace='thoughts'))
    
]

clock/urls.py
from django.urls import path 
from . import views

app_name = 'clock'

urlpatterns = [
    path("", views.Clock.as_view(), name="clock"),
    path("alarm", views.Alarm.as_view(), name="alarm"),
    path("stopwatch", views.StopWatch.as_view(), name="stopwatch"),
    path("pomodoro", views.Pomodoro.as_view(), name="pomodoro"),
    path("timer", views.Timer.as_view(), name="timer"),
    path("worldclock", views.WorldClock.as_view(), name="worldclock")
]

thoughts/urls.py
from django.urls import path 
from . import views

app_name = 'thoughts'

urlpatterns = [
    path('', views.Thoughts.as_view(), name="thoughts"),
    path('write', views.Write.as_view(), name="write"),
    path('library', views.Library.as_view(), name="library"),
    path('categories', views.Categories.as_view(), name="categories"),
    path('archived', views.Archived.as_view(), name="archived")
]

todolist/urls.py
from django.urls import path 
from . import views

app_name = 'todolist'

urlpatterns = [
    path('', views.Today.as_view(), name="today"),
    path('starred', views.Starred.as_view(), name="starred"),
    path('schedule', views.Schedule.as_view(), name="schedule"),
    path('completed', views.Completed.as_view(), name="completed"),
    path('all', views.All.as_view(), name="all"),
    path('overdue', views.Overdue.as_view(), name="overdue"),
    path('create-task/', views.CreateTask.as_view(), name='create_task'),
    path('delete/<slug:title>/', views.DeleteTask.as_view(), name='delete_task'),
]

users/urls.py
from django.urls import path 
from . import views

app_name = "users"

urlpatterns = [
    path('', views.Profile.as_view(), name="profile"),
    path('signup', views.Register.as_view(), name="signup"),
    path('login/', views.Login.as_view(), name="login"),
]

thoughts/models.py
from django.db import models

# Create your models here.
class Thoughts(models.Model):
    pass 

thoughts/views.py
from django.shortcuts import render
from django.views import View 

# Create your views here.
class Thoughts(View):
    def get(self, request):
        return render(request, 'thoughts/dashboard.html')
    
class Write(View):
    def get(self, request):
        return render(request, 'thoughts/write.html')
    
class Library(View):
    def get(self, request):
        return render(request, 'thoughts/library.html')

class Categories(View): 
    def get(self, request):
        return render(request, 'thoughts/categories.html')

class Archived(View):
    def get(self, request):
        return render(request, 'thoughts/archived.html')

thoughts/templates/thoughts/archived.html
{% extends 'thoughts/thoughts.html' %}
{% load static %}
{% block title %}Archived{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}

thoughts/templates/thoughts/categories.html
{% extends 'thoughts/thoughts.html' %}
{% load static %}
{% block title %}Categories{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}
    

thoughts/templates/thoughts/dashboard.html
{% extends 'thoughts/thoughts.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}

{% block CSS %}

<link rel="stylesheet" href="{% static 'thoughts/main/css/dashbord.css' %}">

{% endblock CSS %}
{% block body %}
<div class="search-container">
    <div class="input-group mb-3 mt-5">
      <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button">Search</button>
      </div>
    </div>
  </div>
{% endblock body %}
    

thoughts/templates/thoughts/library.html
{% extends 'thoughts/thoughts.html' %}
{% load static %}
{% block title %}Library{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}
    

thoughts/templates/thoughts/thoughts.html
{% extends 'shared/layout.html' %}
{% load static %}
{% block title %}{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% block nav %}
    <!-- Sidebar Menu Pane -->
    <div class="menu-pane fixed top-0 left-[-30vw] bg-black text-white w-[17vw] h-full transition-transform duration-300 ease-in-out">
        <div class="p-5">
            <div class="text-white mb-6 mt-12">
                <input type="text" placeholder="Search" class="w-full p-2 bg-gray-700 text-white rounded">
            </div>

            <!-- Menu Items -->
            <ul class="space-y-4">
                <li class="flex items-center">
                    <i class="fas fa-cloud mr-3"></i>
                    <a href="{% url 'thoughts:thoughts' %}" class="text-white hover:text-gray-400">Thoughts</a>
                </li>
                <li class="flex items-center">
                    <i class="fas fa-pen-nib mr-3"></i>
                    <a href="{% url 'thoughts:write' %}" class="text-white hover:text-gray-400">Write a thought</a>
                </li>
                <li class="flex items-center">
                    <i class="fas fa-book-open mr-3"></i>
                    <a href="{% url 'thoughts:library' %}" class="text-white hover:text-gray-400">Library</a>
                </li>
                <li class="flex items-center">
                    <i class="fas fa-list mr-3"></i>
                    <a href="{% url 'thoughts:categories' %}" class="text-white hover:text-gray-400">Categories</a>
                </li>
                <li class="flex items-center">
                    <i class="fas fa-warehouse mr-3"></i>
                    <a href="{% url 'thoughts:archived' %}" class="text-white hover:text-gray-400">Archived</a>
                </li>
            </ul>
        </div>
        <!-- Bottom Icons -->
        <div class="absolute bottom-0 w-full flex justify-around py-4 text-white">
            <!-- Clock Icon -->
            <div class="text-center">
                <a href="{% url 'clock:clock' %}" class="text-white hover:text-gray-400">
                    <i class="fas fa-clock fa-2x"></i>
                </a>
                <p class="text-sm mt-1">Clock</p>
            </div>
            
            <!-- Thoughts Icon -->
            <div class="text-center">
                <a href="{% url 'todolist:today' %}" class="text-white hover:text-gray-400">
                    <i class="fas fa-clipboard-list fa-2x"></i>
                </a>
                <p class="text-sm mt-1">TODO</p>
            </div>
            
            <!-- Profile Icon -->
            <div class="text-center">
                <a href="{% url 'users:profile' %}" class="text-white hover:text-gray-400">
                    <i class="fas fa-user fa-2x"></i>
                </a>
                <p class="text-sm mt-1">Profile</p>
            </div>
        </div>
    </div>
{% endblock nav %}

{% include 'thoughts/dashboard.html' %}

{% endblock body %}
    

thoughts/templates/thoughts/write.html
{% extends 'thoughts/thoughts.html' %}
{% load static %}
{% block title %}Write a Thought{% endblock title %}

{% block CSS %}
{% endblock CSS %}

{% block body %}
{% endblock body %}
    